//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHL.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHL.Resources.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string Base_Entity_ID {
            get {
                return ResourceManager.GetString("Base_Entity_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateAt 的本地化字符串。
        /// </summary>
        public static string Base_Entity_UpdateDateLayout {
            get {
                return ResourceManager.GetString("Base_Entity_UpdateDateLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Common_Button_Add {
            get {
                return ResourceManager.GetString("Common_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Common_Button_Browse {
            get {
                return ResourceManager.GetString("Common_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Common_Button_Close {
            get {
                return ResourceManager.GetString("Common_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Common_Button_Delete {
            get {
                return ResourceManager.GetString("Common_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        public static string Common_Button_Down {
            get {
                return ResourceManager.GetString("Common_Button_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Common_Button_Import {
            get {
                return ResourceManager.GetString("Common_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Common_Button_Remove {
            get {
                return ResourceManager.GetString("Common_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Common_Button_Reset {
            get {
                return ResourceManager.GetString("Common_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Common_Button_Save {
            get {
                return ResourceManager.GetString("Common_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Common_Button_Search {
            get {
                return ResourceManager.GetString("Common_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowPostData 的本地化字符串。
        /// </summary>
        public static string Common_Button_ShowPostData {
            get {
                return ResourceManager.GetString("Common_Button_ShowPostData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Common_Button_Submit {
            get {
                return ResourceManager.GetString("Common_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        public static string Common_Button_Up {
            get {
                return ResourceManager.GetString("Common_Button_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing _START_ to _END_ of _TOTAL_ entries 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_info {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing 0 to 0 of 0 entries 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoEmpty {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (filtered from _MAX_ total entries) 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoFiltered {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show _MENU_ entries 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_lengthMenu {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_lengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_first {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_last {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_next {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_previous {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching records found 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_zeroRecords {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_zeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Common_Label_Add {
            get {
                return ResourceManager.GetString("Common_Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string Common_Label_All {
            get {
                return ResourceManager.GetString("Common_Label_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Common_Label_Danger {
            get {
                return ResourceManager.GetString("Common_Label_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Common_Label_Info {
            get {
                return ResourceManager.GetString("Common_Label_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string Common_Label_No {
            get {
                return ResourceManager.GetString("Common_Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Selected 的本地化字符串。
        /// </summary>
        public static string Common_Label_NotSelected {
            get {
                return ResourceManager.GetString("Common_Label_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Common_Label_Remove {
            get {
                return ResourceManager.GetString("Common_Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Common_Label_Success {
            get {
                return ResourceManager.GetString("Common_Label_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Common_Label_Warning {
            get {
                return ResourceManager.GetString("Common_Label_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, the current version in UI is not equals the database, it seems to another user are updating this entity, please refresh this page to get the latest version of this first before you do anything. 的本地化字符串。
        /// </summary>
        public static string Common_Result_Error_VersionNotEqual {
            get {
                return ResourceManager.GetString("Common_Result_Error_VersionNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version Info 的本地化字符串。
        /// </summary>
        public static string Common_Result_Info_CurrentVersionInfo {
            get {
                return ResourceManager.GetString("Common_Result_Info_CurrentVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store {0}  Avail not enough: you send out:  {1} SKU, not there are: {2} remaining only 的本地化字符串。
        /// </summary>
        public static string Delivery_Avail_Not_Enough {
            get {
                return ResourceManager.GetString("Delivery_Avail_Not_Enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Cancel {
            get {
                return ResourceManager.GetString("Delivery_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Delete {
            get {
                return ResourceManager.GetString("Delivery_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Finish {
            get {
                return ResourceManager.GetString("Delivery_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inbound 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Inbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outbound 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Outbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Process {
            get {
                return ResourceManager.GetString("Delivery_Button_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Recevied 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Receive {
            get {
                return ResourceManager.GetString("Delivery_Button_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Ship {
            get {
                return ResourceManager.GetString("Delivery_Button_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shipment Handle 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Shipment {
            get {
                return ResourceManager.GetString("Delivery_Button_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BadOrder 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_BadOrder {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_BadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Cancel {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivering 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Delivering {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_New {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Processing {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Received {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submited 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Submited {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Success {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PurchaseIn 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_PurchaseIn {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_PurchaseIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SellingOut 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_SellingOut {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_SellingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_Transfer {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carriers 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Carriers {
            get {
                return ResourceManager.GetString("Delivery_Label_Carriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_DON {
            get {
                return ResourceManager.GetString("Delivery_Label_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FromStore 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_FromStore {
            get {
                return ResourceManager.GetString("Delivery_Label_FromStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select items from inventory table and click button inbound to add 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Inbound_AddMsg {
            get {
                return ResourceManager.GetString("Delivery_Label_Inbound_AddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InBoundDelivery 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_InBoundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_InBoundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InQty 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_InQty {
            get {
                return ResourceManager.GetString("Delivery_Label_InQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewDelivery 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Delivery 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewInBoundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewInBoundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New PurchaseIn Inbound Deliver 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewPurchaseInDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewPurchaseInDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select items from inventory table and click button outbound to add 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Outbound_AddMsg {
            get {
                return ResourceManager.GetString("Delivery_Label_Outbound_AddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Transfer Outbound Delivery 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Outbound_Select_New {
            get {
                return ResourceManager.GetString("Delivery_Label_Outbound_Select_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutboundDelivery 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutboundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_OutboundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutQty 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutQty {
            get {
                return ResourceManager.GetString("Delivery_Label_OutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Product {
            get {
                return ResourceManager.GetString("Delivery_Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeliveryPurchase In 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_PurchaseInNoSource {
            get {
                return ResourceManager.GetString("Delivery_Label_PurchaseInNoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeliverySelling Out 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SellingOutNoTarget {
            get {
                return ResourceManager.GetString("Delivery_Label_SellingOutNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SKU {
            get {
                return ResourceManager.GetString("Delivery_Label_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusNew {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToStore 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_ToStore {
            get {
                return ResourceManager.GetString("Delivery_Label_ToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SrcStore is Empty 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_SrcStore_Empty {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_SrcStore_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source store could not equal the target store 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_SrcStoreCannotEqualTarStore {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_SrcStoreCannotEqualTarStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Store Can not Equal Source Store 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_TargetCannotEqualSource {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_TargetCannotEqualSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_CancelOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_CancelOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ConfirmOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ConfirmOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Inbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_DeleteInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_DeleteInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_DeleteOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_DeleteOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish Inbound  Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_FinishInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_FinishInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ProcessOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ProcessOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive Inbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ReceiveInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ReceiveInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Inbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_SubmitInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_SubmitInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_SubmitOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_SubmitOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated by Adjustment 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Adjustment {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated by Delivery 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Delivery {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated by Import 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Import {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Package 的本地化字符串。
        /// </summary>
        public static string Epacket_Button_ConfirmPackage {
            get {
                return ResourceManager.GetString("Epacket_Button_ConfirmPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Print Label 的本地化字符串。
        /// </summary>
        public static string Epacket_Button_GetLabel {
            get {
                return ResourceManager.GetString("Epacket_Button_GetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epacket Shipment Information 的本地化字符串。
        /// </summary>
        public static string Epacket_Label_EpacketShipmentInformation {
            get {
                return ResourceManager.GetString("Epacket_Label_EpacketShipmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Export {
            get {
                return ResourceManager.GetString("Excel_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Import {
            get {
                return ResourceManager.GetString("Excel_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Excel_Label_Export {
            get {
                return ResourceManager.GetString("Excel_Label_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Excel_Label_Import {
            get {
                return ResourceManager.GetString("Excel_Label_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UploadFile 的本地化字符串。
        /// </summary>
        public static string Excel_Label_UploadFile {
            get {
                return ResourceManager.GetString("Excel_Label_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Column: {0} is null in Row: {1} 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportColumnError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Excel File Error 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportFileError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are some problem in row {0} 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportRowError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileName {
            get {
                return ResourceManager.GetString("FileData_Entity_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Type 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .csv with delimited format 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_CSV {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .xls excel 2003 format 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_XLS {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .xlsx excel 2007 above format 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_XLSX {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Rule 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_MapRule {
            get {
                return ResourceManager.GetString("FileData_Entity_MapRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Description 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_MapRuleDescription {
            get {
                return ResourceManager.GetString("FileData_Entity_MapRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Type 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All - Process Entire File, update entire inventory by SKU and if the SKU related inventory does not exist, it will create a new one automatically 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_All {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Only - Process only sku related inventory that do not exist in this store (igonore existing SKU) 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_NewOnly {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_NewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateOnly - Process only the sku related inventory already existed in this store (ignore not existing SKU) 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_UpdateOnly {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_UpdateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Map Rule Item(s) 的本地化字符串。
        /// </summary>
        public static string FileData_Label_SelectMapRuleItem {
            get {
                return ResourceManager.GetString("FileData_Label_SelectMapRuleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THE FILE IS NOT CSV 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotCSV {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THE FILE IS NOT XLS 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotXLS {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THE FILE IS NOT XLSX 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotXLSX {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please download 的本地化字符串。
        /// </summary>
        public static string FileInfo_Result_Success_PleaseDownload {
            get {
                return ResourceManager.GetString("FileInfo_Result_Success_PleaseDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avail 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_Avail {
            get {
                return ResourceManager.GetString("Inventory_Entity_Avail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DiffSum 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_diffSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_diffSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InSum 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_InSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_InSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnHold 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnHold {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnIn 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnIn {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnOut 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnOut {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutSum 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OutSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_OutSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipMiss 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_ShipMiss {
            get {
                return ResourceManager.GetString("Inventory_Entity_ShipMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SwAvail 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_SwAvail {
            get {
                return ResourceManager.GetString("Inventory_Entity_SwAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventories 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Inventories {
            get {
                return ResourceManager.GetString("Inventory_Label_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Tools 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_SearchTools {
            get {
                return ResourceManager.GetString("Inventory_Label_SearchTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stores 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Stores {
            get {
                return ResourceManager.GetString("Inventory_Label_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import FileName Error 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportFileNameError {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportFileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU: {0} Not Exist 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportSkuNotExist {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportSkuNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not select any store to import the inventory 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportStoreNoSelect {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportStoreNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Completed:  total - {0}  success - {1}  的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Success_ExportSuccess {
            get {
                return ResourceManager.GetString("Inventory_Result_Success_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Completed:  total - {0}  success - {1} 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Success_ImportSuccess {
            get {
                return ResourceManager.GetString("Inventory_Result_Success_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_AssType_Enum_Export {
            get {
                return ResourceManager.GetString("MapRule_Entity_AssType_Enum_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_AssType_Enum_Import {
            get {
                return ResourceManager.GetString("MapRule_Entity_AssType_Enum_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_DataType_Enum_Delivery {
            get {
                return ResourceManager.GetString("MapRule_Entity_DataType_Enum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_DataType_Enum_Inventory {
            get {
                return ResourceManager.GetString("MapRule_Entity_DataType_Enum_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_Description {
            get {
                return ResourceManager.GetString("MapRule_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MappingRule 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_MappingRule {
            get {
                return ResourceManager.GetString("MapRule_Label_MappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Items Preview 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_MapRuleItemsPreview {
            get {
                return ResourceManager.GetString("MapRule_Label_MapRuleItemsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {} is not null 的本地化字符串。
        /// </summary>
        public static string MapRule_Result_Error_SaveNameNotEmpty {
            get {
                return ResourceManager.GetString("MapRule_Result_Error_SaveNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Name 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_Column {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Name 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_DisplayName {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorting 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_Sorting {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Delivery {
            get {
                return ResourceManager.GetString("Menu_Label_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current User 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Employee {
            get {
                return ResourceManager.GetString("Menu_Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Home {
            get {
                return ResourceManager.GetString("Menu_Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Inventory {
            get {
                return ResourceManager.GetString("Menu_Label_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Log 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Log {
            get {
                return ResourceManager.GetString("Menu_Label_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Rule 的本地化字符串。
        /// </summary>
        public static string Menu_Label_MapRule {
            get {
                return ResourceManager.GetString("Menu_Label_MapRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Setting {
            get {
                return ResourceManager.GetString("Menu_Label_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stores  的本地化字符串。
        /// </summary>
        public static string Menu_Label_Store {
            get {
                return ResourceManager.GetString("Menu_Label_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inventory of Product: {0} in Source Store: {1} is Empty 的本地化字符串。
        /// </summary>
        public static string Product_Empty {
            get {
                return ResourceManager.GetString("Product_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Price {
            get {
                return ResourceManager.GetString("Product_Entity_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string Product_Entity_ShortTitle {
            get {
                return ResourceManager.GetString("Product_Entity_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Product_Entity_SKU {
            get {
                return ResourceManager.GetString("Product_Entity_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Title 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Title {
            get {
                return ResourceManager.GetString("Product_Entity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Description {
            get {
                return ResourceManager.GetString("Store_Entity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Name {
            get {
                return ResourceManager.GetString("Store_Entity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type {
            get {
                return ResourceManager.GetString("Store_Entity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smart Warehouse 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SmartWarehouse {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SmartWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid Store 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SolidStore {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SolidStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Stores 的本地化字符串。
        /// </summary>
        public static string Store_Label_All {
            get {
                return ResourceManager.GetString("Store_Label_All", resourceCulture);
            }
        }
    }
}
