//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHL.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class th_TH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal th_TH() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHL.Resources.th_TH", typeof(th_TH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string Base_Entity_ID {
            get {
                return ResourceManager.GetString("Base_Entity_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdateAt 的本地化字符串。
        /// </summary>
        public static string Base_Entity_UpdateDateLayout {
            get {
                return ResourceManager.GetString("Base_Entity_UpdateDateLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Common_Button_Add {
            get {
                return ResourceManager.GetString("Common_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Common_Button_Close {
            get {
                return ResourceManager.GetString("Common_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Common_Button_Delete {
            get {
                return ResourceManager.GetString("Common_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Common_Button_Reset {
            get {
                return ResourceManager.GetString("Common_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Common_Button_Save {
            get {
                return ResourceManager.GetString("Common_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Common_Button_Search {
            get {
                return ResourceManager.GetString("Common_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowPostData 的本地化字符串。
        /// </summary>
        public static string Common_Button_ShowPostData {
            get {
                return ResourceManager.GetString("Common_Button_ShowPostData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Common_Button_Submit {
            get {
                return ResourceManager.GetString("Common_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing _START_ to _END_ of _TOTAL_ entries 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_info {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing 0 to 0 of 0 entries 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoEmpty {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (filtered from _MAX_ total entries) 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoFiltered {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show _MENU_ entries 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_lengthMenu {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_lengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_first {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_last {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_next {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_previous {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching records found 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_zeroRecords {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_zeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string Common_Label_All {
            get {
                return ResourceManager.GetString("Common_Label_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Cancel {
            get {
                return ResourceManager.GetString("Delivery_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Delete {
            get {
                return ResourceManager.GetString("Delivery_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inbound 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Inbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outbound 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Outbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Process {
            get {
                return ResourceManager.GetString("Delivery_Button_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Ship {
            get {
                return ResourceManager.GetString("Delivery_Button_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_CancelOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Label_CancelOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carriers 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Carriers {
            get {
                return ResourceManager.GetString("Delivery_Label_Carriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_ConfirmOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Label_ConfirmOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_DeleteOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Label_DeleteOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_DON {
            get {
                return ResourceManager.GetString("Delivery_Label_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FromStore 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_FromStore {
            get {
                return ResourceManager.GetString("Delivery_Label_FromStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewDelivery 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutboundDelivery 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutboundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_OutboundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutQty 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutQty {
            get {
                return ResourceManager.GetString("Delivery_Label_OutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_ProcessOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Label_ProcessOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Product {
            get {
                return ResourceManager.GetString("Delivery_Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SKU {
            get {
                return ResourceManager.GetString("Delivery_Label_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 badOrder 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusBadOrder {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusBadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cancel 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusCancel {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delivering 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusDelivering {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusDelivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusError {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 new 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusNew {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 processing 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusProcessing {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 received 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusReceived {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 submited 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusSubmited {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 success 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_StatusSuccess {
            get {
                return ResourceManager.GetString("Delivery_Label_StatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Outbound Delivery Success 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SubmitOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Label_SubmitOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToStore 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_ToStore {
            get {
                return ResourceManager.GetString("Delivery_Label_ToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Export {
            get {
                return ResourceManager.GetString("Excel_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Import {
            get {
                return ResourceManager.GetString("Excel_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avail 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_Avail {
            get {
                return ResourceManager.GetString("Inventory_Entity_Avail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DiffSum 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_diffSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_diffSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InSum 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_InSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_InSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnHold 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnHold {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnIn 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnIn {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnOut 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnOut {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutSum 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OutSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_OutSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipMiss 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_ShipMiss {
            get {
                return ResourceManager.GetString("Inventory_Entity_ShipMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SwAvail 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_SwAvail {
            get {
                return ResourceManager.GetString("Inventory_Entity_SwAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventories 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Inventories {
            get {
                return ResourceManager.GetString("Inventory_Label_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Tools 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_SearchTools {
            get {
                return ResourceManager.GetString("Inventory_Label_SearchTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stores 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Stores {
            get {
                return ResourceManager.GetString("Inventory_Label_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delivery 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Delivery {
            get {
                return ResourceManager.GetString("Menu_Label_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current User 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Employee {
            get {
                return ResourceManager.GetString("Menu_Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Home {
            get {
                return ResourceManager.GetString("Menu_Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Inventory {
            get {
                return ResourceManager.GetString("Menu_Label_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Log 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Log {
            get {
                return ResourceManager.GetString("Menu_Label_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Rule 的本地化字符串。
        /// </summary>
        public static string Menu_Label_MapRule {
            get {
                return ResourceManager.GetString("Menu_Label_MapRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Setting {
            get {
                return ResourceManager.GetString("Menu_Label_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stores  的本地化字符串。
        /// </summary>
        public static string Menu_Label_Store {
            get {
                return ResourceManager.GetString("Menu_Label_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Price {
            get {
                return ResourceManager.GetString("Product_Entity_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string Product_Entity_ShortTitle {
            get {
                return ResourceManager.GetString("Product_Entity_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Product_Entity_SKU {
            get {
                return ResourceManager.GetString("Product_Entity_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Title 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Title {
            get {
                return ResourceManager.GetString("Product_Entity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Description {
            get {
                return ResourceManager.GetString("Store_Entity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Name {
            get {
                return ResourceManager.GetString("Store_Entity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type {
            get {
                return ResourceManager.GetString("Store_Entity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smart Warehouse 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SmartWarehouse {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SmartWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid Store 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SolidStore {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SolidStore", resourceCulture);
            }
        }
    }
}
