//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHL.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHL.Resources.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string Base_Entity_ID {
            get {
                return ResourceManager.GetString("Base_Entity_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        public static string Base_Entity_UpdateDateLayout {
            get {
                return ResourceManager.GetString("Base_Entity_UpdateDateLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Common_Button_Add {
            get {
                return ResourceManager.GetString("Common_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string Common_Button_Browse {
            get {
                return ResourceManager.GetString("Common_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Common_Button_Close {
            get {
                return ResourceManager.GetString("Common_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Common_Button_Delete {
            get {
                return ResourceManager.GetString("Common_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string Common_Button_Down {
            get {
                return ResourceManager.GetString("Common_Button_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Common_Button_Import {
            get {
                return ResourceManager.GetString("Common_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Common_Button_Remove {
            get {
                return ResourceManager.GetString("Common_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Common_Button_Reset {
            get {
                return ResourceManager.GetString("Common_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Common_Button_Save {
            get {
                return ResourceManager.GetString("Common_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Common_Button_Search {
            get {
                return ResourceManager.GetString("Common_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示数据 的本地化字符串。
        /// </summary>
        public static string Common_Button_ShowPostData {
            get {
                return ResourceManager.GetString("Common_Button_ShowPostData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Common_Button_Submit {
            get {
                return ResourceManager.GetString("Common_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string Common_Button_Up {
            get {
                return ResourceManager.GetString("Common_Button_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 _PAGE_ 页 ( 总共 _PAGES_ 页 ) 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_info {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无记录 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoEmpty {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (从 _MAX_ 条记录过滤) 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoFiltered {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页 _MENU_ 条记录 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_lengthMenu {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_lengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_first {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_last {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_next {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_previous {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到记录 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_zeroRecords {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_zeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Common_Label_Add {
            get {
                return ResourceManager.GetString("Common_Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有 的本地化字符串。
        /// </summary>
        public static string Common_Label_All {
            get {
                return ResourceManager.GetString("Common_Label_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Common_Label_Danger {
            get {
                return ResourceManager.GetString("Common_Label_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Common_Label_Info {
            get {
                return ResourceManager.GetString("Common_Label_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string Common_Label_No {
            get {
                return ResourceManager.GetString("Common_Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择 的本地化字符串。
        /// </summary>
        public static string Common_Label_NotSelected {
            get {
                return ResourceManager.GetString("Common_Label_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Common_Label_Remove {
            get {
                return ResourceManager.GetString("Common_Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Common_Label_Success {
            get {
                return ResourceManager.GetString("Common_Label_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意 的本地化字符串。
        /// </summary>
        public static string Common_Label_Warning {
            get {
                return ResourceManager.GetString("Common_Label_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，操作失败，当前您正在操作的实体，界面的版本号与数据库版本号不相等，造成这个原因很有可能是其他同事在您提交之前修改过您正在修改的记录，故此，请先刷新一次页面，再进行业务操作。 的本地化字符串。
        /// </summary>
        public static string Common_Result_Error_VersionNotEqual {
            get {
                return ResourceManager.GetString("Common_Result_Error_VersionNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统版本信息 的本地化字符串。
        /// </summary>
        public static string Common_Result_Info_CurrentVersionInfo {
            get {
                return ResourceManager.GetString("Common_Result_Info_CurrentVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货仓{0}存余量信息不足,您发出的SKU: {1} ,只剩下: {2} 的本地化字符串。
        /// </summary>
        public static string Delivery_Avail_Not_Enough {
            get {
                return ResourceManager.GetString("Delivery_Avail_Not_Enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Cancel {
            get {
                return ResourceManager.GetString("Delivery_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Delete {
            get {
                return ResourceManager.GetString("Delivery_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结单 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Finish {
            get {
                return ResourceManager.GetString("Delivery_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Inbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Outbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Process {
            get {
                return ResourceManager.GetString("Delivery_Button_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认收货 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Receive {
            get {
                return ResourceManager.GetString("Delivery_Button_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Ship {
            get {
                return ResourceManager.GetString("Delivery_Button_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货运处理 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Shipment {
            get {
                return ResourceManager.GetString("Delivery_Button_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坏单 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_BadOrder {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_BadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Cancel {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输中 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Delivering {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Error {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建货运单 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_New {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Processing {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已收货 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Received {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Submited {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Success {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购入 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_PurchaseIn {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_PurchaseIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销出 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_SellingOut {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_SellingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调拨 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_Transfer {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输方式 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Carriers {
            get {
                return ResourceManager.GetString("Delivery_Label_Carriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_DON {
            get {
                return ResourceManager.GetString("Delivery_Label_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发出仓 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_FromStore {
            get {
                return ResourceManager.GetString("Delivery_Label_FromStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请从库存列表选择一些记录，然后点击【入库】增加。 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Inbound_AddMsg {
            get {
                return ResourceManager.GetString("Delivery_Label_Inbound_AddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_InboundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_InboundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入货数量 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_InQty {
            get {
                return ResourceManager.GetString("Delivery_Label_InQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新单 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建购货入库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewInBoundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewInBoundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建购货入库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewPurchaseInDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewPurchaseInDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请从库存列表选择一些记录，然后点击【出库】增加。 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Outbound_AddMsg {
            get {
                return ResourceManager.GetString("Delivery_Label_Outbound_AddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建调拨出库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Outbound_Select_New {
            get {
                return ResourceManager.GetString("Delivery_Label_Outbound_Select_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutboundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_OutboundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出货数量 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutQty {
            get {
                return ResourceManager.GetString("Delivery_Label_OutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Product {
            get {
                return ResourceManager.GetString("Delivery_Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购货入库 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_PurchaseInNoSource {
            get {
                return ResourceManager.GetString("Delivery_Label_PurchaseInNoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售出库 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SellingOutNoTarget {
            get {
                return ResourceManager.GetString("Delivery_Label_SellingOutNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SKU {
            get {
                return ResourceManager.GetString("Delivery_Label_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的仓 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_ToStore {
            get {
                return ResourceManager.GetString("Delivery_Label_ToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出货仓不能为空 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_SrcStore_Empty {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_SrcStore_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货仓不能与收货仓相同 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_SrcStoreCannotEqualTarStore {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_SrcStoreCannotEqualTarStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的仓不能与出货仓相同 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_TargetCannotEqualSource {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_TargetCannotEqualSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功取消出库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_CancelOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_CancelOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功确认出库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ConfirmOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ConfirmOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功删除入库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_DeleteInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_DeleteInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功删除出库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_DeleteOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_DeleteOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成订单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_FinishInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_FinishInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功处理出库单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ProcessOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ProcessOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功收货入库 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ReceiveInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ReceiveInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功提交出货单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_SubmitInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_SubmitInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功提交入货单 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_SubmitOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_SubmitOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由库存调整影响 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Adjustment {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由货运单影响 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Delivery {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由导入影响 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Import {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认包裹 的本地化字符串。
        /// </summary>
        public static string Epacket_Button_ConfirmPackage {
            get {
                return ResourceManager.GetString("Epacket_Button_ConfirmPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获得打印贴标 的本地化字符串。
        /// </summary>
        public static string Epacket_Button_GetLabel {
            get {
                return ResourceManager.GetString("Epacket_Button_GetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epacket 包裹货运信息 的本地化字符串。
        /// </summary>
        public static string Epacket_Label_EpacketShipmentInformation {
            get {
                return ResourceManager.GetString("Epacket_Label_EpacketShipmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Export {
            get {
                return ResourceManager.GetString("Excel_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Import {
            get {
                return ResourceManager.GetString("Excel_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Excel_Label_Export {
            get {
                return ResourceManager.GetString("Excel_Label_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Excel_Label_Import {
            get {
                return ResourceManager.GetString("Excel_Label_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        public static string Excel_Label_UploadFile {
            get {
                return ResourceManager.GetString("Excel_Label_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名: {0} ,第 {1} 行数据是NULL 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportColumnError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Excel文件异常 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportFileError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0} 行的数据有问题 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportRowError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileName {
            get {
                return ResourceManager.GetString("FileData_Entity_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件类型 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .csv 格式 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_CSV {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .xls excel 2003 格式 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_XLS {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .xlsx excel 2007 或以上格式 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_XLSX {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配规则 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_MapRule {
            get {
                return ResourceManager.GetString("FileData_Entity_MapRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则描述 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_MapRuleDescription {
            get {
                return ResourceManager.GetString("FileData_Entity_MapRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理类型 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 - 处理整个文件, 通过SKU更新库存，如果发现指定的仓库没有库存记录，则自动创建一条 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_All {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只处理新建 - 只创建SKU在指定仓库没有库存的记录 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_NewOnly {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_NewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只处理更新 - 只更新指定仓库有该SKU的记录，不会创建任何新记录 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_UpdateOnly {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_UpdateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中的规则项 的本地化字符串。
        /// </summary>
        public static string FileData_Label_SelectMapRuleItem {
            get {
                return ResourceManager.GetString("FileData_Label_SelectMapRuleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该文件不是CSV文件 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotCSV {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该文件不是XLS文件 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotXLS {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该文件不是XLSX文件 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotXLSX {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请下载 的本地化字符串。
        /// </summary>
        public static string FileInfo_Result_Success_PleaseDownload {
            get {
                return ResourceManager.GetString("FileInfo_Result_Success_PleaseDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_Avail {
            get {
                return ResourceManager.GetString("Inventory_Entity_Avail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 差异 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_DiffSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_DiffSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收总 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_InSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_InSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnHold {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在途入 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnIn {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在途出 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnOut {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出总 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OutSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_OutSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输遗失 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_ShipMiss {
            get {
                return ResourceManager.GetString("Inventory_Entity_ShipMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能可用 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_SwAvail {
            get {
                return ResourceManager.GetString("Inventory_Entity_SwAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存列表 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Inventories {
            get {
                return ResourceManager.GetString("Inventory_Label_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_SearchTools {
            get {
                return ResourceManager.GetString("Inventory_Label_SearchTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Stores {
            get {
                return ResourceManager.GetString("Inventory_Label_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名后缀不正确 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportFileNameError {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportFileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU: {0}  不存在 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportSkuNotExist {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportSkuNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要导入的仓库 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportStoreNoSelect {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportStoreNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出完成:  总共 - {0}  成功 - {1} 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Success_ExportSuccess {
            get {
                return ResourceManager.GetString("Inventory_Result_Success_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入完成:  总共 - {0}  成功 - {1} 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Success_ImportSuccess {
            get {
                return ResourceManager.GetString("Inventory_Result_Success_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_AssType_Enum_Export {
            get {
                return ResourceManager.GetString("MapRule_Entity_AssType_Enum_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_AssType_Enum_Import {
            get {
                return ResourceManager.GetString("MapRule_Entity_AssType_Enum_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货运记录 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_DataType_Enum_Delivery {
            get {
                return ResourceManager.GetString("MapRule_Entity_DataType_Enum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存记录 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_DataType_Enum_Inventory {
            get {
                return ResourceManager.GetString("MapRule_Entity_DataType_Enum_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_Description {
            get {
                return ResourceManager.GetString("MapRule_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_MappingRule {
            get {
                return ResourceManager.GetString("MapRule_Label_MappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则预览 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_MapRuleItemsPreview {
            get {
                return ResourceManager.GetString("MapRule_Label_MapRuleItemsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能为空 的本地化字符串。
        /// </summary>
        public static string MapRule_Result_Error_SaveNameNotEmpty {
            get {
                return ResourceManager.GetString("MapRule_Result_Error_SaveNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统名 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_Column {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_DisplayName {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_Sorting {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货运管理 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Delivery {
            get {
                return ResourceManager.GetString("Menu_Label_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Employee {
            get {
                return ResourceManager.GetString("Menu_Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Home {
            get {
                return ResourceManager.GetString("Menu_Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存管理 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Inventory {
            get {
                return ResourceManager.GetString("Menu_Label_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Log {
            get {
                return ResourceManager.GetString("Menu_Label_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入导出规则设置 的本地化字符串。
        /// </summary>
        public static string Menu_Label_MapRule {
            get {
                return ResourceManager.GetString("Menu_Label_MapRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Setting {
            get {
                return ResourceManager.GetString("Menu_Label_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库设置 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Store {
            get {
                return ResourceManager.GetString("Menu_Label_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品{0}在发货仓{1} 已经为空  的本地化字符串。
        /// </summary>
        public static string Product_Empty {
            get {
                return ResourceManager.GetString("Product_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Description {
            get {
                return ResourceManager.GetString("Product_Entity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Price {
            get {
                return ResourceManager.GetString("Product_Entity_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string Product_Entity_ShortTitle {
            get {
                return ResourceManager.GetString("Product_Entity_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Product_Entity_SKU {
            get {
                return ResourceManager.GetString("Product_Entity_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库名称 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Name {
            get {
                return ResourceManager.GetString("Store_Entity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品长名称 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Title {
            get {
                return ResourceManager.GetString("Store_Entity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库类型 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type {
            get {
                return ResourceManager.GetString("Store_Entity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能仓 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SmartWarehouse {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SmartWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传统仓 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SolidStore {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SolidStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有仓库 的本地化字符串。
        /// </summary>
        public static string Store_Label_All {
            get {
                return ResourceManager.GetString("Store_Label_All", resourceCulture);
            }
        }
    }
}
