//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHL.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_HK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_HK() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHL.Resources.zh_HK", typeof(zh_HK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 編號 的本地化字符串。
        /// </summary>
        public static string Base_Entity_ID {
            get {
                return ResourceManager.GetString("Base_Entity_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新時間 的本地化字符串。
        /// </summary>
        public static string Base_Entity_UpdateDateLayout {
            get {
                return ResourceManager.GetString("Base_Entity_UpdateDateLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Common_Button_Add {
            get {
                return ResourceManager.GetString("Common_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瀏覽 的本地化字符串。
        /// </summary>
        public static string Common_Button_Browse {
            get {
                return ResourceManager.GetString("Common_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關閉 的本地化字符串。
        /// </summary>
        public static string Common_Button_Close {
            get {
                return ResourceManager.GetString("Common_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刪除 的本地化字符串。
        /// </summary>
        public static string Common_Button_Delete {
            get {
                return ResourceManager.GetString("Common_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string Common_Button_Down {
            get {
                return ResourceManager.GetString("Common_Button_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入 的本地化字符串。
        /// </summary>
        public static string Common_Button_Import {
            get {
                return ResourceManager.GetString("Common_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Common_Button_Remove {
            get {
                return ResourceManager.GetString("Common_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Common_Button_Reset {
            get {
                return ResourceManager.GetString("Common_Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Common_Button_Save {
            get {
                return ResourceManager.GetString("Common_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查詢 的本地化字符串。
        /// </summary>
        public static string Common_Button_Search {
            get {
                return ResourceManager.GetString("Common_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顯示數據 的本地化字符串。
        /// </summary>
        public static string Common_Button_ShowPostData {
            get {
                return ResourceManager.GetString("Common_Button_ShowPostData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Common_Button_Submit {
            get {
                return ResourceManager.GetString("Common_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string Common_Button_Up {
            get {
                return ResourceManager.GetString("Common_Button_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 _PAGE_ 頁 ( 總共 _PAGES_ 頁 ) 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_info {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無記錄 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoEmpty {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (從 _MAX_ 條記錄過濾) 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_infoFiltered {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每頁 _MENU_ 條記錄 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_lengthMenu {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_lengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首頁 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_first {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾頁 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_last {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下壹頁 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_next {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上壹頁 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_paginate_previous {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_paginate_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沒有找到記錄 的本地化字符串。
        /// </summary>
        public static string Common_DataTable_Label_zeroRecords {
            get {
                return ResourceManager.GetString("Common_DataTable_Label_zeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Common_Label_Add {
            get {
                return ResourceManager.GetString("Common_Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有 的本地化字符串。
        /// </summary>
        public static string Common_Label_All {
            get {
                return ResourceManager.GetString("Common_Label_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 錯誤 的本地化字符串。
        /// </summary>
        public static string Common_Label_Danger {
            get {
                return ResourceManager.GetString("Common_Label_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Common_Label_Info {
            get {
                return ResourceManager.GetString("Common_Label_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編號 的本地化字符串。
        /// </summary>
        public static string Common_Label_No {
            get {
                return ResourceManager.GetString("Common_Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未選擇 的本地化字符串。
        /// </summary>
        public static string Common_Label_NotSelected {
            get {
                return ResourceManager.GetString("Common_Label_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Common_Label_Remove {
            get {
                return ResourceManager.GetString("Common_Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Common_Label_Success {
            get {
                return ResourceManager.GetString("Common_Label_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 註意 的本地化字符串。
        /// </summary>
        public static string Common_Label_Warning {
            get {
                return ResourceManager.GetString("Common_Label_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系統版本信息 的本地化字符串。
        /// </summary>
        public static string Common_Result_Info_CurrentVersionInfo {
            get {
                return ResourceManager.GetString("Common_Result_Info_CurrentVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貨倉{0}存余量信息不足,您發出的SKU: {1} ,只剩下: {2} 的本地化字符串。
        /// </summary>
        public static string Delivery_Avail_Not_Enough {
            get {
                return ResourceManager.GetString("Delivery_Avail_Not_Enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Cancel {
            get {
                return ResourceManager.GetString("Delivery_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刪除 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Delete {
            get {
                return ResourceManager.GetString("Delivery_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 結單 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Finish {
            get {
                return ResourceManager.GetString("Delivery_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入庫 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Inbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出庫 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Outbound {
            get {
                return ResourceManager.GetString("Delivery_Button_Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 處理 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Process {
            get {
                return ResourceManager.GetString("Delivery_Button_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確認收貨 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Receive {
            get {
                return ResourceManager.GetString("Delivery_Button_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 發貨 的本地化字符串。
        /// </summary>
        public static string Delivery_Button_Ship {
            get {
                return ResourceManager.GetString("Delivery_Button_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 壞單 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_BadOrder {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_BadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Cancel {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 運輸中 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Delivering {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 異常 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Error {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建貨運單 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_New {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 處理中 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Processing {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已收貨 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Received {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Submited {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Status_Enum_Success {
            get {
                return ResourceManager.GetString("Delivery_Entity_Status_Enum_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 購入 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_PurchaseIn {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_PurchaseIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 銷出 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_SellingOut {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_SellingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調撥 的本地化字符串。
        /// </summary>
        public static string Delivery_Entity_Type_Enum_Transfer {
            get {
                return ResourceManager.GetString("Delivery_Entity_Type_Enum_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 運輸方式 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Carriers {
            get {
                return ResourceManager.GetString("Delivery_Label_Carriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 狀態 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_DON {
            get {
                return ResourceManager.GetString("Delivery_Label_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 發出倉 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_FromStore {
            get {
                return ResourceManager.GetString("Delivery_Label_FromStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請從庫存列表選擇壹些記錄，然後點擊【入庫】增加。 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Inbound_AddMsg {
            get {
                return ResourceManager.GetString("Delivery_Label_Inbound_AddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入庫 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_InboundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_InboundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入貨數量 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_InQty {
            get {
                return ResourceManager.GetString("Delivery_Label_InQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新單 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建購貨入庫單 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_NewInBoundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_NewInBoundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請從庫存列表選擇壹些記錄，然後點擊【出庫】增加。 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Outbound_AddMsg {
            get {
                return ResourceManager.GetString("Delivery_Label_Outbound_AddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出庫 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutboundDelivery {
            get {
                return ResourceManager.GetString("Delivery_Label_OutboundDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出貨數量 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_OutQty {
            get {
                return ResourceManager.GetString("Delivery_Label_OutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 產品 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_Product {
            get {
                return ResourceManager.GetString("Delivery_Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 購貨入庫 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_PurchaseInNoSource {
            get {
                return ResourceManager.GetString("Delivery_Label_PurchaseInNoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 銷售出庫 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SellingOutNoTarget {
            get {
                return ResourceManager.GetString("Delivery_Label_SellingOutNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_SKU {
            get {
                return ResourceManager.GetString("Delivery_Label_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的倉 的本地化字符串。
        /// </summary>
        public static string Delivery_Label_ToStore {
            get {
                return ResourceManager.GetString("Delivery_Label_ToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 發貨倉不能與收貨倉相同 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_SrcStoreCannotEqualTarStore {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_SrcStoreCannotEqualTarStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的倉不能與出貨倉相同 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Error_TargetCannotEqualSource {
            get {
                return ResourceManager.GetString("Delivery_Result_Error_TargetCannotEqualSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功取消出庫單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_CancelOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_CancelOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功確認出庫單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ConfirmOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ConfirmOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功刪除入庫單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_DeleteInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_DeleteInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功刪除出庫單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_DeleteOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_DeleteOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成訂單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_FinishInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_FinishInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功處理出庫單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ProcessOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ProcessOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功收貨入庫 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_ReceiveInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_ReceiveInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功提交出貨單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_SubmitInboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_SubmitInboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功提交入貨單 的本地化字符串。
        /// </summary>
        public static string Delivery_Result_Success_SubmitOutboundDeliverySuccess {
            get {
                return ResourceManager.GetString("Delivery_Result_Success_SubmitOutboundDeliverySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由庫存調整影響 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Adjustment {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由貨運單影響 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Delivery {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由導入影響 的本地化字符串。
        /// </summary>
        public static string DeliveryLog_Entity_Type_Enum_Import {
            get {
                return ResourceManager.GetString("DeliveryLog_Entity_Type_Enum_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導出 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Export {
            get {
                return ResourceManager.GetString("Excel_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入 的本地化字符串。
        /// </summary>
        public static string Excel_Button_Import {
            get {
                return ResourceManager.GetString("Excel_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導出 的本地化字符串。
        /// </summary>
        public static string Excel_Label_Export {
            get {
                return ResourceManager.GetString("Excel_Label_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入 的本地化字符串。
        /// </summary>
        public static string Excel_Label_Import {
            get {
                return ResourceManager.GetString("Excel_Label_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上傳文件 的本地化字符串。
        /// </summary>
        public static string Excel_Label_UploadFile {
            get {
                return ResourceManager.GetString("Excel_Label_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名: {0} ,第 {1} 行數據是NULL 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportColumnError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入Excel文件異常 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportFileError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0} 行的數據有問題 的本地化字符串。
        /// </summary>
        public static string ExcelHelper_Result_Error_ImportRowError {
            get {
                return ResourceManager.GetString("ExcelHelper_Result_Error_ImportRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileName {
            get {
                return ResourceManager.GetString("FileData_Entity_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件類型 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .csv 格式 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_CSV {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .xls excel 2003 格式 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_XLS {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .xlsx excel 2007 或以上格式 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_FileType_Enum_XLSX {
            get {
                return ResourceManager.GetString("FileData_Entity_FileType_Enum_XLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配規則 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_MapRule {
            get {
                return ResourceManager.GetString("FileData_Entity_MapRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 規則描述 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_MapRuleDescription {
            get {
                return ResourceManager.GetString("FileData_Entity_MapRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 處理類型 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 - 處理整個文件, 通過SKU更新庫存，如果發現指定的倉庫沒有庫存記錄，則自動創建壹條 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_All {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只處理新建 - 只創建SKU在指定倉庫沒有庫存的記錄 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_NewOnly {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_NewOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只處理更新 - 只更新指定倉庫有該SKU的記錄，不會創建任何新記錄 的本地化字符串。
        /// </summary>
        public static string FileData_Entity_ProcessType_Enum_UpdateOnly {
            get {
                return ResourceManager.GetString("FileData_Entity_ProcessType_Enum_UpdateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選中的規則項 的本地化字符串。
        /// </summary>
        public static string FileData_Label_SelectMapRuleItem {
            get {
                return ResourceManager.GetString("FileData_Label_SelectMapRuleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 該文件不是CSV文件 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotCSV {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 該文件不是XLS文件 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotXLS {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 該文件不是XLSX文件 的本地化字符串。
        /// </summary>
        public static string FileData_Result_Error_NotXLSX {
            get {
                return ResourceManager.GetString("FileData_Result_Error_NotXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_Avail {
            get {
                return ResourceManager.GetString("Inventory_Entity_Avail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 差異 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_DiffSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_DiffSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收總 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_InSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_InSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鎖定 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnHold {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在途入 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnIn {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在途出 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OnOut {
            get {
                return ResourceManager.GetString("Inventory_Entity_OnOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出總 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_OutSum {
            get {
                return ResourceManager.GetString("Inventory_Entity_OutSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 運輸遺失 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_ShipMiss {
            get {
                return ResourceManager.GetString("Inventory_Entity_ShipMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能可用 的本地化字符串。
        /// </summary>
        public static string Inventory_Entity_SwAvail {
            get {
                return ResourceManager.GetString("Inventory_Entity_SwAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 庫存列表 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Inventories {
            get {
                return ResourceManager.GetString("Inventory_Label_Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查詢 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_SearchTools {
            get {
                return ResourceManager.GetString("Inventory_Label_SearchTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倉庫 的本地化字符串。
        /// </summary>
        public static string Inventory_Label_Stores {
            get {
                return ResourceManager.GetString("Inventory_Label_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名後綴不正確 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportFileNameError {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportFileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU: {0}  不存在 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportSkuNotExist {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportSkuNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選擇要導入的倉庫 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Error_ImportStoreNoSelect {
            get {
                return ResourceManager.GetString("Inventory_Result_Error_ImportStoreNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導出完成:  總共 - {0}  成功 - {1} 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Success_ExportSuccess {
            get {
                return ResourceManager.GetString("Inventory_Result_Success_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入完成:  總共 - {0}  成功 - {1} 的本地化字符串。
        /// </summary>
        public static string Inventory_Result_Success_ImportSuccess {
            get {
                return ResourceManager.GetString("Inventory_Result_Success_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導出 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_AssType_Enum_Export {
            get {
                return ResourceManager.GetString("MapRule_Entity_AssType_Enum_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_AssType_Enum_Import {
            get {
                return ResourceManager.GetString("MapRule_Entity_AssType_Enum_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貨運記錄 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_DataType_Enum_Delivery {
            get {
                return ResourceManager.GetString("MapRule_Entity_DataType_Enum_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 庫存記錄 的本地化字符串。
        /// </summary>
        public static string MapRule_Entity_DataType_Enum_Inventory {
            get {
                return ResourceManager.GetString("MapRule_Entity_DataType_Enum_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_Description {
            get {
                return ResourceManager.GetString("MapRule_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 規則 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_MappingRule {
            get {
                return ResourceManager.GetString("MapRule_Label_MappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 規則預覽 的本地化字符串。
        /// </summary>
        public static string MapRule_Label_MapRuleItemsPreview {
            get {
                return ResourceManager.GetString("MapRule_Label_MapRuleItemsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不能為空 的本地化字符串。
        /// </summary>
        public static string MapRule_Result_Error_SaveNameNotEmpty {
            get {
                return ResourceManager.GetString("MapRule_Result_Error_SaveNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系統名 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_Column {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顯示名 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_DisplayName {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string MapRuleItem_Entity_Sorting {
            get {
                return ResourceManager.GetString("MapRuleItem_Entity_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貨運管理 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Delivery {
            get {
                return ResourceManager.GetString("Menu_Label_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 當前用戶 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Employee {
            get {
                return ResourceManager.GetString("Menu_Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首頁 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Home {
            get {
                return ResourceManager.GetString("Menu_Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 庫存管理 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Inventory {
            get {
                return ResourceManager.GetString("Menu_Label_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日誌 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Log {
            get {
                return ResourceManager.GetString("Menu_Label_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入導出規則設置 的本地化字符串。
        /// </summary>
        public static string Menu_Label_MapRule {
            get {
                return ResourceManager.GetString("Menu_Label_MapRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設置 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Setting {
            get {
                return ResourceManager.GetString("Menu_Label_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倉庫設置 的本地化字符串。
        /// </summary>
        public static string Menu_Label_Store {
            get {
                return ResourceManager.GetString("Menu_Label_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品{0}在發貨倉{1} 已經為空  的本地化字符串。
        /// </summary>
        public static string Product_Empty {
            get {
                return ResourceManager.GetString("Product_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Description {
            get {
                return ResourceManager.GetString("Product_Entity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 價格 的本地化字符串。
        /// </summary>
        public static string Product_Entity_Price {
            get {
                return ResourceManager.GetString("Product_Entity_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 產品名稱 的本地化字符串。
        /// </summary>
        public static string Product_Entity_ShortTitle {
            get {
                return ResourceManager.GetString("Product_Entity_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SKU 的本地化字符串。
        /// </summary>
        public static string Product_Entity_SKU {
            get {
                return ResourceManager.GetString("Product_Entity_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倉庫名稱 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Name {
            get {
                return ResourceManager.GetString("Store_Entity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 產品長名稱 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Title {
            get {
                return ResourceManager.GetString("Store_Entity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倉庫類型 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type {
            get {
                return ResourceManager.GetString("Store_Entity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能倉 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SmartWarehouse {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SmartWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 傳統倉 的本地化字符串。
        /// </summary>
        public static string Store_Entity_Type_Enum_SolidStore {
            get {
                return ResourceManager.GetString("Store_Entity_Type_Enum_SolidStore", resourceCulture);
            }
        }
    }
}
